// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDdX6UluEIGLNnvniUXRre42wnJ-P2uc',
    appId: '1:951778885818:web:e60eeb607b077b9aa68283',
    messagingSenderId: '951778885818',
    projectId: 'gov-complaints-project',
    authDomain: 'gov-complaints-project.firebaseapp.com',
    storageBucket: 'gov-complaints-project.firebasestorage.app',
    measurementId: 'G-93D7170NJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNCWs_O3HP56u7y_i1UedWjw9Y4sa2zvA',
    appId: '1:951778885818:android:eb2fd9bc9c902710a68283',
    messagingSenderId: '951778885818',
    projectId: 'gov-complaints-project',
    storageBucket: 'gov-complaints-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrhLAwU_RbRM0k-RHos5VIjq2REOc0B70',
    appId: '1:951778885818:ios:60d2e279e987ed42a68283',
    messagingSenderId: '951778885818',
    projectId: 'gov-complaints-project',
    storageBucket: 'gov-complaints-project.firebasestorage.app',
    iosBundleId: 'com.example.compaintsystem',
  );
}
